version: "3.8"
services:
  web:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - data:/data
      - ..:/app
    ports:
      - 3000:3000
    env_file:
      - .env  # Automatically load all variables from this file
    command:
      - pnpm
      - web
    working_dir: /app
    depends_on:
      prep:
        condition: service_completed_successfully
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    ports:
      - 9222:9222
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    volumes:
      - meilisearch:/meili_data
  workers:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - data:/data
      - ..:/app
    env_file:
      - .env
    working_dir: /app
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      # OPENAI_API_KEY: ...
    command:
      - pnpm
      - workers
    depends_on:
      prep:
        condition: service_completed_successfully
  prep:
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    working_dir: /app
    environment:
      DATA_DIR: /data
    volumes:
      - data:/data
      - ..:/app
    command:
     - /bin/sh
     - -c
     - "pnpm install --frozen-lockfile && pnpm run db:migrate"

volumes:
  meilisearch:
  data:
