version: "3.8"
services:
  web:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - data:/data
      - ..:/app
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
    command:
      - pnpm
      - web
    working_dir: /app
    depends_on:
      prep:
        condition: service_completed_successfully
  redis:
    image: redis:7.2-alpine
    volumes:
      - redis:/data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.6
    volumes:
      - meilisearch:/meili_data
  workers:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - data:/data
      - ..:/app
    working_dir: /app
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      # OPENAI_API_KEY: ...
    command:
      - pnpm
      - workers
    depends_on:
      prep:
        condition: service_completed_successfully
  prep:
    build:
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      DATA_DIR: /data
    volumes:
      - data:/data
      - ..:/app
    command:
      - /bin/sh
      - -c
      - "corepack enable && pnpm install --frozen-lockfile && pnpm run db:migrate"

volumes:
  redis:
  meilisearch:
  data:
